In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [2]:
df = pd.read_csv('autism1.csv') 
print(df.shape)
df.describe().transpose()

(704, 12)

           count      mean       std  min  25%  50%  75%  max
A1_Score   704.0  0.721591  0.448535  0.0  0.0  1.0  1.0  1.0
A2_Score   704.0  0.453125  0.498152  0.0  0.0  0.0  1.0  1.0
A3_Score   704.0  0.457386  0.498535  0.0  0.0  0.0  1.0  1.0
A4_Score   704.0  0.495739  0.500337  0.0  0.0  0.0  1.0  1.0
A5_Score   704.0  0.498580  0.500353  0.0  0.0  0.0  1.0  1.0
A6_Score   704.0  0.284091  0.451301  0.0  0.0  0.0  1.0  1.0
A7_Score   704.0  0.417614  0.493516  0.0  0.0  0.0  1.0  1.0
A8_Score   704.0  0.649148  0.477576  0.0  0.0  1.0  1.0  1.0
A9_Score   704.0  0.323864  0.468281  0.0  0.0  0.0  1.0  1.0
A10_Score  704.0  0.573864  0.494866  0.0  0.0  1.0  1.0  1.0
jundice    704.0  0.098011  0.297541  0.0  0.0  0.0  0.0  1.0
ASD        704.0  0.268466  0.443476  0.0  0.0  0.0  1.0  1.0

In [3]:
target_column = ['ASD'] 
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

           count      mean       std  min  25%  50%  75%  max
A1_Score   704.0  0.721591  0.448535  0.0  0.0  1.0  1.0  1.0
A2_Score   704.0  0.453125  0.498152  0.0  0.0  0.0  1.0  1.0
A3_Score   704.0  0.457386  0.498535  0.0  0.0  0.0  1.0  1.0
A4_Score   704.0  0.495739  0.500337  0.0  0.0  0.0  1.0  1.0
A5_Score   704.0  0.498580  0.500353  0.0  0.0  0.0  1.0  1.0
A6_Score   704.0  0.284091  0.451301  0.0  0.0  0.0  1.0  1.0
A7_Score   704.0  0.417614  0.493516  0.0  0.0  0.0  1.0  1.0
A8_Score   704.0  0.649148  0.477576  0.0  0.0  1.0  1.0  1.0
A9_Score   704.0  0.323864  0.468281  0.0  0.0  0.0  1.0  1.0
A10_Score  704.0  0.573864  0.494866  0.0  0.0  1.0  1.0  1.0
jundice    704.0  0.098011  0.297541  0.0  0.0  0.0  0.0  1.0
ASD        704.0  0.268466  0.443476  0.0  0.0  0.0  1.0  1.0

In [4]:
X = df[predictors].values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=45)
print(X_train.shape); print(X_test.shape)

(563, 11)
(141, 11)

In [5]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(5,8,5), activation='relu', solver='adam', max_iter=1000)
mlp.fit(X_train,y_train.ravel())

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [6]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[412   0]
 [  0 151]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       412
           1       1.00      1.00      1.00       151

    accuracy                           1.00       563
   macro avg       1.00      1.00      1.00       563
weighted avg       1.00      1.00      1.00       563

In [7]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[103   0]
 [  2  36]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       103
           1       1.00      0.95      0.97        38

    accuracy                           0.99       141
   macro avg       0.99      0.97      0.98       141
weighted avg       0.99      0.99      0.99       141